import streamlit as st
import pandas as pd
import pymysql
# Load MySQL credentials from Streamlit secrets
MYSQL_CONF = st.secrets["mysql"]
def get_connection():
    return pymysql.connect(
        host=MYSQL_CONF["host"],
        user=MYSQL_CONF["user"],
        password=MYSQL_CONF["password"],
        database=MYSQL_CONF["db"],
        port=int(MYSQL_CONF["port"])
    )

def init_db():
    conn = get_connection()
    # Initialize your database here
    conn.close()

def load_bets_from_db():
    conn = get_connection()
    df = pd.read_sql_query("SELECT * FROM bets", conn)
    conn.close()
    return df

def insert_bet(bet):
    conn = get_connection()
    # Insert your bet into the database here
    conn.close()

def delete_bets(bet_ids):
    conn = get_connection()
    # Delete your bets from the database here
    conn.close()

def delete_all_bets():
    conn = get_connection()
    # Delete all bets from the database here
    conn.close()
